services:
    hafas-client:
        container_name: hafas-client
        image: schmolldechsee/hafas-rest:latest
        restart: always
        ports:
            - "3000:3000"
        networks:
            - hafas-network

networks:
    hafas-network:
        external: true
