services:
    hafas-rest:
        container_name: hafas-rest
        image: schmolldechsee/hafas-rest:latest
        restart: always
        ports:
            - "15000:15000"
            - "15100:15100"
        networks:
            - hafas-network

networks:
    hafas-network:
        external: true
