name: build server and push docker image

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name: installing dependencies
          working-directory: server
          run: npm install

        - name: build image
          run: docker build -t hafas-rest:latest ./server

        - name: log in to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: push docker image
          run: docker tag hafas-rest:latest ${{ secrets.DOCKER_USERNAME }}/hafas-rest:latest
        - run: docker push ${{ secrets.DOCKER_USERNAME }}/hafas-rest:latest
